### PR TITLE
Tree-sitter 0.15

### PR DESCRIPTION
**Pull request by 314eter**
I removed support for null characters. It's not working anymore since tree-sitter 0.15, and nobody uses them.

For some reason, `isspace` was not working in webassembly. It allowed more characters than the OCaml specification anyway, so the new implementation is better.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
> For some reason, `isspace` was not working in webassembly.

You could actually use the wide character variant `iswspace` instead.

The reason `isspace` isn't available is that Emscripten's "dynamic linking" mode doesn't allow "side module" libraries like these to have their own library dependencies - instead, all of the necessary C/C++ standard library functions must be included into the main `web-tree-sitter` module. I have [a script](https://github.com/tree-sitter/tree-sitter/blob/master/script/generate-wasm-exports-list) in the `tree-sitter` repo that generates a list of all of the necessary standard library functions, based on the [list of parsers](https://github.com/tree-sitter/tree-sitter/blob/0e046fc6c00e6deb06cea8b346698cfaee442620/script/fetch-fixtures#L24-L35) that we test `tree-sitter` with. The current output is [here](https://github.com/tree-sitter/tree-sitter/blob/master/lib/binding_web/exports.json). As you can see, it includes all of the wide character variants of the `ctypes` APIs, but not that `char`-based ones.

**Comment by 314eter** [comment]
I fixed the tests and added support for new features in OCaml 4.08 (I think that deserves a new release).

The tests are still failing because Travis tested the wrong commit after I rebased.

**Comment by 314eter** [comment]
I tried to use only the functions included in `web-tree-sitter`. It's a little bit strange that `towupper` is included but `towlower` is not.

The only problem left is the `assign` in `deserialize`.

**Comment by maxbrunsfeld** [comment]
I can add some functions in the next release of `web-tree-sitter`.

**Pull request merged**
