### PR TITLE
Add action to publish releases on NPM

### PR DESCRIPTION
**Pull request by 314eter**
@maxbrunsfeld @aryx Someone with access to NPM will have to add the `NPM_TOKEN` secret to get this working.

### CODE REVIEW

**Comment by aryx** [comment]
I don't have access. maybe @dcreager ?

**Comment by 314eter** [comment]
@maxbrunsfeld I see [node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter) is using a github action for publishing to NPM now. Does that mean there is an `NPM_TOKEN` secret added to the tree-sitter organization that can work for tree-sitter-ocaml too?

If not, can you either add me as maintainer on NPM (so I can release manually), or add an `NPM_TOKEN` secret (so this PR can be merged)?

The NPM release of tree-sitter-ocaml is already two years behind now.

**Comment by amaanq** [comment]
i don't, Max needs to add that to the org 😬

**Comment by amaanq** [comment]
Ok, Max has added the token org-wide so this can be merged @314eter

**Review by aryx — APPROVED** [review]

**Comment by 314eter** [comment]
It works :partying_face:

**Pull request merged**
