### PR TITLE
Add node fields

### PR DESCRIPTION
**Pull request by 314eter**
I'm trying to add supertypes and node fields.

The first commits introduces supertypes. There were a lot of candidates, but most of them needed some refactoring (making the attributes part of the subtypes).

Then I added field names, but disabled them by redefining `field()`. The tests are still passing.

When I enable `field()`, the tests are failing.

### CODE REVIEW

**Comment by 314eter** [comment]
@maxbrunsfeld There are a lot of compilation warnings (https://travis-ci.org/tree-sitter/tree-sitter-ocaml/builds/624822810#L221). Is it possible that adding too much fields overflows the `uint8_t` `production_id`?

**Comment by maxbrunsfeld** [comment]
> Is it possible that adding too much fields overflows the `uint8_t production_id`?

Oh yes, that is probably what's happening 😱.

The `production_id` field [originated](https://github.com/tree-sitter/tree-sitter/pull/90/commits/b3a72954ff389a0655557c58266feea4a0cee852#diff-93410268e6218f96d70a6f6c9ae9d469R50) as a `uint8_t` because it was only storing alias information, and there weren't very many distinct productions with aliases. Back then, I was freely changing the parse table format because Tree-sitter wasn't used in Atom yet.

Later, when I added the `field` API, I reused that same field in the parse tables, so as to avoid making a breaking ABI change. But now I guess it's much easier to exceed 255 production ids. I'll have to think about how this can be changed while minimizing the backward-compatibility issues.

**Comment by maxbrunsfeld** [comment]
In the meantime, I guess we have to hold off on adding all of these fields. Maybe you can add *some*, but not all of these.

Separately from that, it would be good to understand why this parser is so much larger than the others in terms of its state count. Maybe there are some optimizations that can be done at the grammar level to shrink it, which might avoid this problem with `production_id`.

**Comment by 314eter** [comment]
I tried to find out why the parser is so large when the binary was still 1GB in size. I didn't find one big problem back then, just a lot of small things that add up, and I simplified what I could. Luckily, optimizations in tree-sitter got the size down a lot since then.

One possible simplification that I was thinking of when I added the supertypes, is moving the attributes to extras. They can appear almost everywhere in the grammar since they can be attached to everything, but they are probably not that important for tree-sitter applications.

**Comment by maxbrunsfeld** [comment]
Just in case it's helpful, I'll share one thing that I've done to investigate parser size. There's a flag called `--report-states-for-rule` that prints some information about the state machien. You can run it first like this, to get a summary:

```
tree-sitter generate --report-states-for-rule -
```

<details>
<summary>Output</summary>

```
infix_expression                       	998
product_expression                     	886
cons_expression                        	886
sequence_expression                    	671
value_name                             	549
object_copy_expression                 	288
record_expression                      	273
fun_expression                         	272
string_get_expression                  	266
array_get_expression                   	266
bigarray_get_expression                	266
package_expression                     	209
_extension_attribute                   	202
class_binding                          	200
function_type                          	187
value_definition_repeat1               	182
aliased_type                           	180
object_expression                      	168
hash_type                              	165
quoted_extension                       	161
coercion_expression                    	161
_simple_expression                     	161
match_expression                       	160
constructor_declaration                	156
let_binding                            	154
constructor_path                       	153
list_expression                        	144
array_expression                       	144
field_get_expression                   	138
method_invocation                      	137
if_expression                          	136
local_open_expression                  	135
polymorphic_variant_type               	132
constructed_type                       	132
typed_expression                       	129
try_expression                         	128
module_type_constraint                 	125
_hash_expression                       	123
functor                                	117
submodule                              	117
functor_type                           	115
extension                              	115
module_application                     	114
_definitions_repeat2                   	109
match_case                             	104
list_expression_repeat1                	102
object_copy_expression_repeat1         	101
record_expression_repeat1              	99
set_expression                         	96
value_definition                       	91
object_type                            	90
method_definition                      	79
class_path                             	76
value_path                             	73
string                                 	72
for_expression                         	72
instance_variable_definition           	71
let_exception_expression               	70
let_open_expression                    	70
let_module_expression                  	70
let_binding_repeat1                    	69
field_path                             	69
alias_pattern                          	68
parameter                              	66
cons_pattern                           	66
tuple_pattern                          	66
or_pattern                             	66
unit                                   	65
parenthesized_expression               	65
new_expression                         	64
_match_cases                           	60
quoted_string                          	59
attribute                              	55
let_expression                         	54
character                              	54
type_binding                           	53
_match_cases_repeat1                   	52
prefix_expression                      	51
_simple_module_expression              	51
_sign_expression                       	49
module_type_constraint_repeat1         	47
record_pattern                         	45
package_pattern                        	42
module_binding                         	40
labeled_argument                       	39
value_definition_repeat2               	39
type_constructor_path                  	39
function_expression                    	38
object_expression_repeat1              	38
package_type                           	38
module_type_path                       	37
class_function_type                    	36
tag                                    	36
class_application_repeat1              	34
indexing_operator_path                 	34
_argument                              	34
_definitions                           	32
then_clause                            	32
else_clause                            	32
while_expression                       	32
module_binding_repeat1                 	30
class_type_binding                     	30
array_pattern                          	27
type_binding_repeat1                   	27
list_pattern                           	27
class_function                         	26
_definitions_repeat3                   	24
typed_pattern                          	24
_expression                            	24
list_pattern_repeat1                   	24
tuple_type                             	23
_extension                             	23
polymorphic_variant_type_repeat1       	23
record_declaration                     	22
parenthesized_type                     	22
constructor_argument                   	21
local_open_pattern                     	21
assert_expression                      	20
lazy_expression                        	20
module_definition                      	20
attribute_id_repeat1                   	20
open_statement                         	20
string_repeat1                         	20
item_attribute                         	20
do_clause                              	20
label                                  	20
instantiated_class                     	19
_definitions_repeat1                   	19
application_expression                 	19
object_type_repeat1                    	19
number                                 	18
class_definition                       	18
boolean                                	18
class_body_type                        	18
_constant                              	18
module_type_of                         	18
polymorphic_variant_type_repeat2       	17
class_definition_repeat1               	17
class_type_path                        	16
_type_equation                         	16
_module_type                           	16
constructor_argument_repeat1           	16
packed_module                          	16
module_definition_repeat1              	16
record_declaration_repeat1             	15
instantiated_class_type_repeat1        	14
typed_module_expression                	14
signature                              	14
external                               	14
structure                              	14
type_variable                          	14
parenthesized_pattern                  	14
_simple_or_tuple_type                  	13
module_type_definition                 	13
let_open_class_expression              	13
inheritance_definition                 	13
method_specification                   	13
instance_variable_specification        	13
type_constraint                        	12
record_pattern_repeat1                 	12
exception_definition                   	12
module_parameter                       	12
_poly_type                             	12
class_binding_repeat1                  	11
tag_specification                      	11
attribute_id                           	10
type_definition                        	10
typed_class_expression                 	10
_typed_label                           	10
_type                                  	10
_class_expression                      	10
value_specification                    	10
let_open_class_type                    	10
_simple_class_type                     	9
_simple_pattern                        	9
_simple_type                           	9
class_type_definition                  	9
let_class_expression                   	9
parenthesized_module_expression        	9
attribute_payload                      	9
class_application                      	8
type_parameter_constraint              	8
instantiated_class_type                	8
lazy_pattern                           	8
exception_pattern                      	8
type_definition_repeat1                	8
include_statement                      	8
_tuple_pattern_no_exn                  	7
quoted_item_extension                  	7
field_expression                       	7
method_specification_repeat1           	7
instance_variable_specification_repeat1	7
class_type_definition_repeat1          	7
field_declaration                      	7
_alias_pattern_no_exn                  	7
_or_pattern_no_exn                     	7
polymorphic_pattern                    	7
field_pattern                          	7
_specifications_repeat1                	7
_signed_number                         	7
_cons_pattern_no_exn                   	7
class_initializer                      	6
_comment_repeat1                       	6
type_params                            	6
parenthesized_class_expression         	6
class_body_type_repeat1                	6
parenthesized_module_type              	6
range_pattern                          	6
variant_declaration_repeat1            	5
_extended_module_name_repeat1          	5
tag_specification_repeat1              	5
_type_param                            	5
variant_declaration                    	5
_module_expression                     	5
item_extension                         	5
floating_attribute                     	5
polymorphic_types_repeat1              	4
external_repeat1                       	4
refutation_case                        	4
_class_type                            	4
_pattern                               	4
_comment                               	4
comment                                	4
inheritance_specification              	4
type_params_repeat1                    	4
constructor_pattern                    	4
tag_pattern                            	4
method_type                            	3
_extended_module_name                  	3
_signed_constant                       	3
toplevel_directive                     	3
_tag_spec                              	3
compilation_unit                       	3
_module_item                           	3
module_path                            	3
abstract_type_repeat1                  	3
_specifications                        	3
_sign_operator                         	2
directive                              	2
escape_sequence                        	2
_simple_class_expression               	2
_pattern_no_exn                        	2
_class_field                           	2
_class_field_specification             	2
polymorphic_types                      	2
abstract_type                          	2
_assign_operator                       	1
_or_operator                           	1
_and_operator                          	1
infix_operator                         	1
_item_extension                        	1
_instance_variable_name                	0
_method_name                           	0
_class_name                            	0
_field_name                            	0
_type_constructor                      	0
_module_name                           	0
_mult_operator                         	0
_constructor_name                      	0
_seq_expression                        	0
_label_name                            	0
_module_type_name                      	0
_pow_operator                          	0
```

</details>

That's just showing the *number* of parse states where a given rule is in-progress. The numbers don't add up to the total state count, because a given parse state can contain multiple in-progress rules. Then, if you want to get more details for a particular rule, you can supply the rule name. It will show you a logical representation of all of the parse states containing that rule (extremely verbose).

```
tree-sitter generate --report-states-for-rule value_name
```

This data can be very hard to interpret, but sometimes it can give you ideas about why the parser might be so large.

**Comment by 314eter** [comment]
I wanted to move attributes to extras to simplify the parse tree, but it doesn't seem to work.

@maxbrunsfeld Is it intentional that inside a non-terminal extra other non-terminal extras are not allowed? So if both comments (`(* ... *)`) and attributes (`[@attr ... ]`) are non-terminal extras, then
```ocaml
[@attr (* comment *) ]
```
is impossible to parse.

**Comment by maxbrunsfeld** [comment]
> Is it intentional that inside a non-terminal extra other non-terminal extras are not allowed?

Yeah, that's the expected behavior currently. It may be possible to relax it in future versions of the CLI.

**Comment by 314eter** [comment]
Are external scanners allowed in non-terminal extras? Maybe I can revert the comments to an external scanner then.

**Comment by maxbrunsfeld** [comment]
Yeah, external tokens are allowed within non-terminal extras.

> Maybe I can revert the comments to an external scanner then.

I think that may be a good idea, since code-size seems to be a significant concern with this grammar.

**Comment by 314eter** [comment]
I reduced the number of fields. The highest value for `production_id` is now 244, so that's (just) below 256.

The introduction of supertypes increased the number of states significantly, and needed some refactoring to avoid conflicts.
Moving `$.attribute` to extras reduced the number of states, but not as much as I hoped. The introduction of `$._typed` (and variants) reduced the number of states too.
The result is that this PR leaves the number of states roughly the same as before.

**Comment by maxbrunsfeld** [comment]
> The introduction of supertypes

Just to clarify - you did some restructuring of other rules to work better with supertypes? Because I think the supertypes themselves don't change the generated parser.

**Comment by 314eter** [comment]
Yes. Most of the rules that were potential candidates for supertypes were of the form
```js
_expression: $ => prec.right(seq(
  choice(
    $.product_expression,
    $.cons_expression,
    $.application_expression,
    $.infix_expression,
    ...
  ),
  repeat($.attribute)
))
```
which I refactored to
```js
_expression: $ => choice(
  $.product_expression,
  $.cons_expression,
  $.application_expression,
  $.infix_expression,
  ...
)
```
in order to make it a supertype.

**Comment by maxbrunsfeld** [comment]
Oh, I see, thanks. I'm surprised that this change increased the number of states 🤔 . But I think this branch is good to go. 🚢  at will!

**Comment by 314eter** [comment]
Just the refactoring I described -- and thus removing `$.attribute` completely -- decreases the number of states of course.

I initially moved `$.attribute` to every child rule of `$._expression`, which increases the number of states a lot (I'm only mentioning `$._expression`, but there are many rules like this). Then I moved `$.attribute` to extras, which is better, but still worse than it was before.

**Comment by XVilka** [comment]
Please update the submodule here too https://github.com/tree-sitter/haskell-tree-sitter/tree/master/tree-sitter-ocaml

**Comment by 314eter** [comment]
I will, but there are more changes coming.

**Pull request merged**
