### PR TITLE
Support new features (OCaml 4.12+)

### PR DESCRIPTION
**Pull request by 314eter**
- Hash sign in prefix operators (ocaml/ocaml#9429)
- Let punning (ocaml/ocaml#10013)
- Naming existentials in patterns (ocaml/ocaml#9584)
- Module type substitutions (ocaml/ocaml#10133)

### CODE REVIEW

**Comment by 314eter** [comment]
The Github Actions tests don't run apparently, but they are failing: https://github.com/314eter/tree-sitter-ocaml/runs/1994780189

This is not related to changes in this PR, they were fine before I updated the examples in the last commit: https://github.com/314eter/tree-sitter-ocaml/runs/1994761493

With this (same) content in `test.ml` and `test.mli`, `tree-sitter parse test.ml` is fine but `tree-sitter parse test.mli` fails.
```ocaml
module type T = sig
  val f : ?x (**) : int -> int
end
```
This is really weird, since the `ocaml` and `interface` parsers are almost the same. The comment is parsed by an external scanner, which does return true, but tree-sitter acts like it returns false and then fails to parse the comment.

@maxbrunsfeld Is this a known bug in tree-sitter? It seems to be solved in tree-sitter 0.18.

**Comment by undu** [comment]
> The Github Actions tests don't run apparently,

I think the branches field for the pull request should be removed, not sure why it's limited to some names
```yaml
  pull_request:
    branches:
      - '**:**'
```

**Comment by 314eter** [comment]
@undu That was indeed the problem, thanks.

**Comment by 314eter** [comment]
I rebased this PR on master, and tree-sitter 0.19 fixes the failing tests.

**Pull request merged**
