### PR TITLE
Support new features

### PR DESCRIPTION
**Pull request by 314eter**
Add support for some new OCaml features.

These changes increased the compile time from 1 minute to 10 minutes. With tree-sitter 0.14.0-beta3 it's only 10 seconds.

### CODE REVIEW

**Comment by 314eter** [comment]
@maxbrunsfeld I don't know why the Travis test fails. Tree-sitter says the files don't exist, but they should. When I run it locally, everything works.

**Comment by maxbrunsfeld** [comment]
> I don't know why the Travis test fails. Tree-sitter says the files don't exist

Sorry about that, I think that bug is fixed by https://github.com/tree-sitter/tree-sitter/commit/92a6a69625e94e5aac65a0ad6118866b1ebf42b6, which I'll release in 0.14.2 shortly.

**Comment by maxbrunsfeld** [comment]
Alright, I rebuilt with the latest `tree-sitter-cli` release and we are ✅ .

**Comment by maxbrunsfeld** [comment]
I'm cool with merging this if it's ready, @314eter.

**Comment by 314eter** [comment]
It's ready.

**Comment by 314eter** [comment]
@maxbrunsfeld Can you do a new release too?

**Pull request merged**
