### PR TITLE
Migrate to tree-sitter 0.16

### PR DESCRIPTION
**Pull request by XVilka**
Required for https://github.com/tree-sitter/haskell-tree-sitter/pull/283

### CODE REVIEW

**Comment by XVilka** [comment]
There is https://github.com/tree-sitter/tree-sitter-ocaml/pull/36 but it is quite outdated.

**Comment by XVilka** [comment]
Not sure the reasons behind the failures though (I am not very familiar with Tree Sitter depths):

## [merlin/tests/test-dirs/errors/typing-after-parsing/test.ml](https://github.com/ocaml/merlin/blob/master/tests/test-dirs/errors/typing-after-parsing/test.ml)
```
0 ms	(ERROR [6, 9] - [6, 10])
```
## [merlin/tests/test-dirs/completion/parenthesize.ml ](https://github.com/ocaml/merlin/blob/master/tests/test-dirs/completion/parenthesize.ml)
```
0 ms	(ERROR [10, 14] - [10, 15])
```
## [merlin/tests/test-dirs/completion/infix.ml](https://github.com/ocaml/merlin/blob/master/tests/test-dirs/completion/infix.ml)
```
0 ms	(ERROR [8, 9] - [8, 10])
```
## [merlin/tests/test-dirs/locate/context-detection/label.ml](https://github.com/ocaml/merlin/blob/master/tests/test-dirs/locate/context-detection/label.ml)
```
0 ms	(ERROR [7, 12] - [7, 14])
```

**Comment by maxbrunsfeld** [comment]
This is probably a bug in the latest parser generator. I will try to look into this soon.

**Comment by 314eter** [comment]
The errors in the merlin tests are known failures, but the test files moved to another directory. The merlin tests includes some files with syntax errors to test the error messages.

There are two failures in the ocaml testsuite too, these are caused by new features (ocaml/ocaml#9232 and ocaml/ocaml#9500). I added them to the known failures for now, and will update the grammar later.

I'm still working on #36. I didn't have a lot of time the last few months, but I hope to get it finished soon. I planned to work on semantic support after that. Since #36 will probably have a big impact on the syntax tree, I wanted to get that finsihed first.

**Comment by maxbrunsfeld** [comment]
Sounds good @314eter, thanks for the update!

**Comment by XVilka** [comment]
Let me know what I can do to get this merged.

**Pull request merged**
