### PR TITLE
Use proper capture group for booleans

### PR DESCRIPTION
**Pull request by silenc3r**
I don't know if I'm doing it right but it seems to work.

### CODE REVIEW

**Comment by 314eter** [comment]
Using a separate capture group for booleans only makes sense if the tools that will use it support this capture group. As far as I know there is no documented set of standard capture groups that are supported by all tools, so I just try to follow other tree-sitter grammars.

Where have you seen the "boolean" capture group being used?

**Comment by silenc3r** [comment]
nvim-treesitter defines it https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/highlight.lua#L18

**Comment by 314eter** [comment]
nvim-treesitter has its own [highlights.scm](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/ocaml/highlights.scm) file. If you want to change the highlighting in Neovim, you have to open a PR there.

**Comment by silenc3r** [comment]
I didn't know that, thanks!

I still think changing it to `constant.builtin` would be sensible. That's what some (most?) other languages do, e.g [Python](https://github.com/tree-sitter/tree-sitter-python/blob/master/queries/highlights.scm#L37), [JavaScript](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/queries/highlights.scm#L76), [Go](https://github.com/tree-sitter/tree-sitter-go/blob/master/queries/highlights.scm#L111), [Ruby](https://github.com/tree-sitter/tree-sitter-ruby/blob/master/queries/highlights.scm#L119)

**Pull request closed without merging**
